# Generated by Django 3.1.7 on 2021-03-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('size', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('purchase_date', models.CharField(max_length=15)),
                ('packaged', models.CharField(max_length=15)),
                ('user', models.CharField(max_length=20)),
                ('post_date', models.CharField(max_length=15)),
                ('image_name', models.CharField(max_length=200)),
                ('order_id', models.IntegerField()),
            ],
        ),
    ]
